---
title: "Rebecca Glassman, MPH"
# image: 

about:
  template: solana
  image-shape: round
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/rebecca-glassman/
    - icon: twitter
      text: Twitter
      href: https://twitter.com/notoriousrsg

---
##### Public Health Researcher and Data Quality Lead
Rebecca Glassman is a public health researcher and serves as the Data Quality Lead at The Pandemic Tracking Collective. Her tasks include co-developing and maintaining a vaccine breakthrough data tracker, science communication, and research. 

Previously, she was a core member of The COVID Tracking Project’s data and science communication teams. Prior to her work with The COVID Tracking Project, Rebecca was a research project manager at the University of Florida’s College of Medicine, where she was responsible for managing a US Centers for Disease Control and Prevention (CDC)-funded youth mental health epidemiology study site. Her responsibilities included assisting with the development of the study methodology, study recruitment, and data management. Her broader research interests include demographic data standardization efforts and LGBTQ+ health. 

Rebecca received her MPH, in addition to her undergraduate health science degree, from the University of North Florida. Rebecca enjoys spending time in the mountains with her wife and dogs.